### ISSUE TITLE
Please add a LICENSE file to this public repository

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/zilla-slab#1]
I don't know which license y'all selected for the font, but that license should be dropped into a LICENSE file and committed here for other users whenever the next set of commits are pushed.

**Comment by alexgibson** [comment]
This is coming with the font, thanks.

**Comment by floatingatoll** [comment]
Sure thing! No rush, just logged for when the rest of the commits arrive. (We can't force Github to *require* one, so the next best things is open issues.)

**Comment by floatingatoll** [comment]
Cheers!
