### ISSUE TITLE
Add LICENSE file to release files

### ISSUE THREAD

**Issue by Skatox** [mozilla/zilla-slab#14]
Hello!
In some Linux distributions, in order to distribute this fonts an license file is required. Is it possible to add the license file from source code to the root of the release files?

So when you download release file it has the license file attached to it. This will help Linux package maintainers to grab license from the same .zip file as the fonts.

**Comment by alexgibson** [comment]
I'll make sure this gets added to future releases, thanks!

**Comment by alexgibson** [comment]
This was fixed in the latest release

**Comment by Skatox** [comment]
Awesome, thanks.
