### ISSUE TITLE
Zilla Highlight in Google Docs has extra space appended to end of sentence

### ISSUE THREAD

**Issue by m4rc1e** [mozilla/zilla-slab#18]
This issue was reported to me in an email thread.

Zilla Highlight uses a liga OpenType feature to make the space appear highlighted by replacing the space glyph with a black variant.

```
lookup BLACKSPACE {
                sub space by space.black;
                sub uni00A0 by space.black;
            } BLACKSPACE;
```

Google Docs appends a `&nbsp;` (uni00A0) to the end of user input. 

```
<span class="kix-wordhtmlgenerator-word-node" style="...">Hello World<span class="goog-inline-block" style="...">&nbsp;</span>
```

This unfortunately produces the following:
![screen shot 2017-08-14 at 11 13 10](https://user-images.githubusercontent.com/7525512/29268056-288fb086-80e3-11e7-8f1f-dfbe6293d8a7.png)

It should look like this:
![screen shot 2017-08-14 at 11 12 49](https://user-images.githubusercontent.com/7525512/29268072-31f295e4-80e3-11e7-9077-1498abe25348.png)

The easiest solution is to drop uni00A0 from the BLACKSPACE lookup:

```
lookup BLACKSPACE {
                sub space by space.black;
            } BLACKSPACE;
```

I'm wondering if anyone can think of any unforeseen consequences by doing this?

**Comment by moyogo** [comment]
> I'm wondering if anyone can think of any unforeseen consequences by doing this?

Some people use uni00A0 on purpose between words or before and after punctuation.

**Comment by m4rc1e** [comment]
@moyogo This was an assumption I had. Thank you!

**Comment by davelab6** [comment]
Right, so if anyone else uses nbsp on purpose, then they won't get the 'blackout' effect in the middle of those words, if Marc changes the feature only to remove the `sub uni00A0 by space.black;` rule. 

The docs for the family could tell people who need to use nbsp with blackout to use another character that does the same thing (https://en.wikipedia.org/wiki/Non-breaking_space#Width_variation) and change that rule to one that uses those other non breaking space characters.

**Comment by moyogo** [comment]
How about substituting uni00A0 only in that context (at the end of the line)?

**Comment by davelab6** [comment]
You mean, substituting it only when it is followed by another character?

**Comment by m4rc1e** [comment]
Thanks @moyogo. I've rewritten the feature in the following manner:
```
sub space by space.black;
sub uni00A0' @all by space.black;
```

This does the following:
- Space will always be subbed by space.black
- uni00A0 will only get substituted if uni00A0 is followed by any glyph in the class `@all`

 
Here's a demo of the liga feature being enabled and disabled. The text uses uni00A0 instead of spaces. A uni00A0 glyph has also been appended to the end to mimic the same pattern as GF Docs. It seems to be working just fine.
![zilla-slab](https://user-images.githubusercontent.com/7525512/29310449-a763e068-81a5-11e7-838e-7279506bd774.gif)

**Comment by m4rc1e** [comment]
The string below has uni00A0 instead of a space... its works nicely.

![screen shot 2017-08-15 at 11 52 41](https://user-images.githubusercontent.com/7525512/29313155-5d293830-81b0-11e7-8bdf-58b9c15f58eb.png)

@davelab6 shall we proceed with this contextual sub approach?

**Comment by davelab6** [comment]
Great work everyone!
