### ISSUE TITLE
Release font on Google Font & Typekit

### ISSUE THREAD

**Issue by irvin** [mozilla/zilla-slab#2]
It would be good to have Zilla on those external sites, that people can easily to sync across computer like Fira.
https://github.com/mozilla/Fira#external-resources

**Comment by davelab6** [comment]
I'm currently responsible for onboarding fonts into Google Fonts and I've been working with Mozilla to queue this up :) Stay tuned!

**Comment by davelab6** [comment]
@gene1wood Should be very soon

**Comment by m4rc1e** [comment]
Can confirm Zilla Slab has made it onto Google Fonts, https://fonts.google.com/specimen/Zilla+Slab

I'll work on getting the highlight family included as well.

**Comment by alexgibson** [comment]
Is it expected that the Google Fonts site doesn't work in Firefox?

<img width="1406" alt="screen shot 2017-07-05 at 10 26 42 am" src="https://user-images.githubusercontent.com/400117/27858275-8a56e6cc-616c-11e7-9e5f-fad2fa2c6c73.png">

**Comment by alexgibson** [comment]
It seems like this is related to https://bugzilla.mozilla.org/show_bug.cgi?id=1331797

**Comment by m4rc1e** [comment]
@alexgibson on my 55.0b6 edition.

Things are smooth

![screen shot 2017-07-05 at 10 33 57](https://user-images.githubusercontent.com/7525512/27858561-9d638f80-616d-11e7-9f1d-c0da4435f1a7.png)

**Comment by alexgibson** [comment]
@m4rc1e can you try on the latest Nightly? https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly

**Comment by m4rc1e** [comment]
Oh bork

![screen shot 2017-07-05 at 10 42 32](https://user-images.githubusercontent.com/7525512/27858852-b3fa106a-616e-11e7-8a5e-539bd3228a1f.png)

**Comment by alexgibson** [comment]
I'm going to open a new issue for this

**Comment by m4rc1e** [comment]
Thanks, I'm looking into it as well.

**Comment by alexgibson** [comment]
I opened a new issue here to discuss: https://github.com/mozilla/zilla-slab/issues/12

**Comment by alexgibson** [comment]
Going to close this issue, as Zilla Slab is now available on Google Fonts. We currently have no plans for Typekit, afaik.

**Comment by irvin** [comment]
Additional question, Zilla Slab Highlight is not available on Google Font. Is it intended?

**Comment by m4rc1e** [comment]
@irvin pr'd yesterday, https://github.com/google/fonts/pull/1074. Will take a few weeks to be on boarded.

**Comment by irvin** [comment]
@m4rc1e cool!

**Comment by potch** [comment]
I added Zilla Slab to our own CDN, alongside the [copy of Fira](https://code.cdn.mozilla.net/fonts/fira.css) that's already there: https://code.cdn.mozilla.net/fonts/zilla-slab.css

Feel free to point folks to it if you want!

**Comment by alexgibson** [comment]
> I added Zilla Slab to our own CDN, alongside the copy of Fira that's already there: https://code.cdn.mozilla.net/fonts/zilla-slab.css

> Feel free to point folks to it if you want!

Great, I'll see if I can add this to the readme. Thanks @potch!
