### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by Pomax** [mozilla/zilla-slab#3]
https://github.com/mozilla/zilla-slab/blob/master/UFOs/ZillaSlab-Regular.ufo/features.fea points to files necessary to compile this font, but not found in the repository.

**Comment by alexgibson** [comment]
I'll see if I can chase this up with the font designer, thanks

**Comment by alexgibson** [comment]
This should now be fixed in #5

**Comment by Pomax** [comment]
awesome, thanks!
