### ISSUE TITLE
Numeric characters are not rendered uniformly

### ISSUE THREAD

**Issue by phsita** [mozilla/zilla-slab#40]
## Issue Snap of PDF Document

![image](https://user-images.githubusercontent.com/25145744/145685854-e033b446-de66-4199-81d4-80c8de52b108.png)

## Details
I made a pdf document from latex using pandoc on a debian buster os. I find the number letters "0123456789" are rendered in a non-uniform fashion.
The one's out of order in my opinion seems to be -
Char-set-1 = { "0" , "1" , "2" } ; these characters appear to be comparatively smaller w.r.t the alphabets
Char-set-2 = { "3" , "4" , "5" , "7" , "9" } ; these characters appear to be placed slightly below the alphabet's lowest line

## Environment

1.   Latex
```
# latex --version
pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020/Debian)
kpathsea version 6.3.2
Copyright 2020 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.02
```

2.   Pandoc
```
# pandoc  --version
pandoc 2.16.1
Compiled with pandoc-types 1.22.1, texmath 0.12.3.2, skylighting 0.12.1,
citeproc 0.6, ipynb 0.1.0.2
User data directory: /root/.local/share/pandoc
Copyright (C) 2006-2021 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

4.   Kernel
```
# uname -a
Linux local 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
```

5.   OS
```
Debian GNU/Linux 11
```

**Comment by fitojb** [comment]
This is not a bug. The figures are Elzevirian (more commonly known as “old-style”).

**Comment by phsita** [comment]
> This is not a bug. The figures are Elzevirian (more commonly known as “old-style”).

That clarifies the doubt. Closed issue.
