### ISSUE TITLE
nbsp characters are not displayed with Zilla font

### ISSUE THREAD

**Issue by alexgibson** [mozilla/zilla-slab#7]
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1366863

**Comment by alexgibson** [comment]
This should be fixed in #5

**Comment by m4rc1e** [comment]
I can confirm we're good.

http://jsbin.com/kaguwalene/edit?html,output


![screen shot 2017-07-05 at 10 03 38](https://user-images.githubusercontent.com/7525512/27857360-444365a0-6169-11e7-9ada-cd031eff8f48.png)
