### ISSUE TITLE
No need to reserve generic font names like weights

### ISSUE THREAD

**Issue by n7s** [mozilla/zilla-slab#9]
Hi guys,

No need to reserve the generic weight names as they are non-unique parts of your font name. It's overkill.
See OFL FAQ section 5.5 on http://scripts.sil.org/ofl-faq_web#7fba289b

(BTW if you haven't read through the FAQ yet, it's probably a good idea to do so).

Thanks.

**Comment by moyogo** [comment]
See PR #5 where RFN is removed.

**Comment by n7s** [comment]
hi @moyogo 

I am well-aware of that branch, I just want to point to the relevant FAQ entry so Mozilla can make decisions about naming for themselves.

**Comment by alexgibson** [comment]
Fixed in #5
